### ISSUE TITLE
Reconsider documentation representation

### ISSUE THREAD

**Issue by nemothenoone** [NilFoundation/crypto3#1]
Currently documentation is being generated by doxygen with no sufficient information representation. No concepts description, no examples, no fine formatting.

Documentation generation script enhancement is a crucial step.

This particular task involves:
- [ ] Resolving all the Doxygen-generated warnings and issues.

**Comment by nkaskov** [comment]
The rows in the tables are locked incorrectly. So hardfix for that is as such: in doxygen.css comment the rule 
```
.directory tr.even {
	padding-left: 6px;
	background-color: #F7F8FB;
}
```

**Comment by nemothenoone** [comment]
> The rows in the tables are locked incorrectly. So hardfix for that is as such: in doxygen.css comment the rule
> 
> ```
> .directory tr.even {
> 	padding-left: 6px;
> 	background-color: #F7F8FB;
> }
> ```

Fixed with setting relevant option in customdoxygen.css to correct value.
