### ISSUE TITLE
Finalize enabling goldilocks64

### ISSUE THREAD

**Issue by akokoshn** [NilFoundation/crypto3#154]
- Arithmetic-parameters for goldilocks64 - `arithmetic_params<goldilocks64_base_field>`
- *tests - `math/tests/evaluate_domian`

**Comment by ETatuzova** [comment]
Please, add placeholder test on goldilocks to this crypto3 branch.
Change ref to zk branch

https://github.com/NilFoundation/crypto3-zk/pull/301
