### ISSUE TITLE
Fix typos in Placeholder test

### ISSUE THREAD

**Issue by 3for** [NilFoundation/crypto3#43]
In both [https://github.com/NilFoundation/crypto3-zk-marshalling/blob/master/test/detail/circuits.hpp#L202](https://github.com/NilFoundation/crypto3-zk-marshalling/blob/master/test/detail/circuits.hpp#L202) and [https://github.com/NilFoundation/crypto3-zk/blob/master/test/systems/plonk/placeholder/circuits.hpp#L202](https://github.com/NilFoundation/crypto3-zk/blob/master/test/systems/plonk/placeholder/circuits.hpp#L202)，the code:
```
add_constraint.add_term(w0 * w1);
add_constraint.add_term(-w2);
```
should be changed to:
```
mul_constraint.add_term(w0 * w1);
mul_constraint.add_term(-w2);
```

**Comment by 3for** [comment]
@nkaskov In the end of `circuit_test_3()`, missing `test_circuit.lookup_gates.push_back(lookup_gate);`?

**Comment by nemothenoone** [comment]
@Luannet this might be interesting for you to take a look into.

**Comment by nemothenoone** [comment]
@3for You're right. Fixed in https://github.com/NilFoundation/crypto3/commit/d2ee0edb034365bdd62218e691f48f3b1c321669.
