### ISSUE TITLE
Create bigger self-hosted runners

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/crypto3#93]
We experience lack-of-memory issues with our current runners: https://github.com/NilFoundation/crypto3/actions/runs/6769935170/job/18397400778?pr=91

Looks like we can solve it by adding new self-hosted runners for CI: https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/managing-larger-runners

**Comment by martun** [comment]
There is a possibility that Posseidon requires more RAM to build, because its constants are too large, and there's a tiny bit of compile-time computation done:

https://github.com/NilFoundation/crypto3-hash/blob/master/include/nil/crypto3/hash/detail/poseidon/original_constants.hpp

**Comment by x-mass** [comment]
Heavy modules use self-hosted runners now:
https://github.com/NilFoundation/ci-cd/blob/master/.github/workflows/reusable-crypto3-testing-linux.yml#L42
